version: "3.4"
services:
  web:
    image: nginx:stable
    privileged: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1k"  
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./mysql-expose.mod:/etc/nginx/conf.d/mysql-expose.mod
      - ./gateway.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - ./config/config.js:/usr/share/nginx/html/config.js
      - ./images:/usr/share/nginx/html/images
      - ./attachments:/usr/share/nginx/html/attachments
    ports:
      - 8086:80